# Generated by Django 4.2.7 on 2023-11-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='have_limit',
            field=models.BooleanField(default=False),
        ),
    ]
